# Generated by Django 2.0 on 2019-06-07 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qu', models.CharField(max_length=20)),
                ('at', models.CharField(max_length=20)),
                ('wa', models.CharField(max_length=20)),
                ('ra', models.CharField(max_length=20)),
                ('marks', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usermodeltest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('usermodeltest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='marks_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.usermodeltest'),
        ),
    ]
