# Generated by Django 2.0 on 2019-06-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bcsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='contcatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentlist', models.CharField(max_length=100)),
                ('cata_pic', models.ImageField(default='cata_folder/None/no-img.jpg', upload_to='cata_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='contentelement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('boxcontent', models.CharField(max_length=50000, null=True)),
                ('content', models.CharField(max_length=45000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contcatagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.contcatagory')),
            ],
        ),
        migrations.CreateModel(
            name='contentelementimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_pic', models.ImageField(default='content_folder/None/no-img.jpg', upload_to='content_folder/')),
                ('title', models.CharField(max_length=100, null=True)),
                ('contentelement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.contentelement')),
            ],
        ),
        migrations.CreateModel(
            name='contenttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qu', models.CharField(max_length=400)),
                ('ans', models.CharField(max_length=100)),
                ('contentelement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.contentelement')),
            ],
        ),
        migrations.CreateModel(
            name='contenttableinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tl1', models.CharField(max_length=450, null=True)),
                ('tl2', models.CharField(max_length=450, null=True)),
                ('tl3', models.CharField(max_length=450, null=True)),
                ('tl4', models.CharField(max_length=450, null=True)),
                ('tl5', models.CharField(max_length=450, null=True)),
                ('tl6', models.CharField(max_length=450, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='contenttabletitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('cl1', models.CharField(max_length=50, null=True)),
                ('cl2', models.CharField(max_length=50, null=True)),
                ('cl3', models.CharField(max_length=50, null=True)),
                ('cl4', models.CharField(max_length=50, null=True)),
                ('cl5', models.CharField(max_length=50, null=True)),
                ('cl6', models.CharField(max_length=50, null=True)),
                ('contenttable_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.contentelement')),
            ],
        ),
        migrations.CreateModel(
            name='imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.ImageField(blank=True, null=True, upload_to='question/')),
            ],
        ),
        migrations.CreateModel(
            name='modelquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('que_pic', models.ImageField(default='que_folder/None/no-img.jpg', upload_to='que_folder/')),
                ('op1', models.CharField(max_length=200)),
                ('op2', models.CharField(max_length=200)),
                ('op3', models.CharField(max_length=200)),
                ('op4', models.CharField(max_length=200)),
                ('ans', models.IntegerField()),
                ('explain', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('que_pic', models.ImageField(default='que_folder/None/no-img.jpg', upload_to='que_folder/')),
                ('op1', models.CharField(max_length=200)),
                ('op2', models.CharField(max_length=200)),
                ('op3', models.CharField(max_length=200)),
                ('op4', models.CharField(max_length=200)),
                ('ans', models.IntegerField()),
                ('explain', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='subcatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100, null=True)),
                ('model_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.contentelement')),
            ],
        ),
        migrations.CreateModel(
            name='tableinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=50)),
                ('tableinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.table')),
            ],
        ),
        migrations.CreateModel(
            name='tabletitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=50)),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.table')),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.contentelement')),
            ],
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionname', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bcs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.bcsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('exp', models.CharField(max_length=300)),
                ('sn', models.CharField(max_length=130)),
                ('an', models.CharField(max_length=130)),
                ('quate', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='wordtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subcatagory',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.subjects'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.subjects'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.types'),
        ),
        migrations.AddField(
            model_name='modelquestion',
            name='modelqusetion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.version'),
        ),
        migrations.AddField(
            model_name='contenttableinfo',
            name='contenttabletitle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.contenttabletitle'),
        ),
        migrations.AddField(
            model_name='contcatagory',
            name='subcatagory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.subcatagory'),
        ),
        migrations.AddField(
            model_name='bcsmodel',
            name='bcsmodel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.contentelement'),
        ),
    ]
