# Generated by Django 2.0 on 2019-06-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subinfo', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='modettests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=190)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subinfo.event')),
            ],
        ),
    ]
