# Generated by Django 2.0 on 2019-06-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.CharField(max_length=6000)),
                ('mean', models.CharField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('editorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editorial.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='meaningelement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=300)),
                ('meaning_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editorial.meaning')),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='editorial_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Editorial.editorial'),
        ),
    ]
